
STOUT = 'stout'
THIN = 'thin'
LACKING = 'lacking'
THIN_LACKING = 'thin to lacking'
ROUND = 'round'
NORTH = 'Northern states'
MIDDLE = 'Middle states'
SOUTH = 'south'
NORTH_MIDDLE = 'northern and middle states'
BOTH = 'Both'
MIDDLE_SOUTH = 'middle and southern states'

needle_length = 'needle length'
distribution = 'dist'
needle_count = 'needles per cluster'
fire_resislience = 'trunk sprouts after fire'
twig_texture = 'twigs rough near needle'
old_cones = 'many old cones on tree'
cone_length = 'cones longer than three inches'
cone_shape = 'cones longer than wide'
cone_prickles = 'cone prickle type'
short_desc = 'short description'
long_desc = 'full description'